# Generated by Django 3.2.12 on 2022-11-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BunchOfLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brandlogo', models.URLField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('upvote', models.IntegerField(default=0, null=True)),
                ('downvote', models.IntegerField(default=0, null=True)),
                ('bookmark', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('colour_code', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(max_length=255)),
                ('bunchoflinks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.bunchoflinks')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('bunch_of_links', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='links.bunchoflinks')),
            ],
        ),
    ]
