# Generated by Django 3.2.12 on 2022-11-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_bunchoflinks_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='bunch_of_links',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bunch_of_links', to='links.bunchoflinks'),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='followers',
            field=models.BooleanField(default=False),
        ),
    ]
